version: "3.9"

services:

  # Frontend: Dashboard en React
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:4000
    depends_on:
      - backend

  # Backend: Orquestador Node.js + Express
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend/builds:/app/builds
      - ./backend/services.json:/app/services.json
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  default:
    name: microservices-net
