version: "3.9"

services:

  # Frontend: Dashboard en React
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:4000
    depends_on:
      - backend

  # Backend: Orquestador Node.js + Express
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - DOCKER_HOST=tcp://host.docker.internal:2375
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./backend/builds:/app/builds
      - ./backend/services.json:/app/services.json

networks:
  default:
    name: microservices-net
